PierresTreats/Models/Flavor.cs
using System.Collections.Generic;

namespace PierresTreats.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.Treats = new HashSet<TreatFlavor>();
    }
    public int FlavorId { get; set; }
    public string FlavorName { get; set; }
    public ICollection<TreatFlavor> Treats { get; set; }
  }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(PierresTreatsContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.Treats)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      IQueryable<TreatFlavor> treatFlavors = _db.TreatFlavors.Where(entry => entry.FlavorId == flavor.FlavorId);
      foreach (TreatFlavor entry in treatFlavors)
      {
        if (entry.TreatId == TreatId)
        {
          return RedirectToAction("Details", new { id = flavor.FlavorId });
        }
      }
      if (TreatId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }
      

    [Authorize]
    public ActionResult DeleteTreat(int id)
    {
      var joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == id);
      ViewBag.Flavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == joinEntry.FlavorId);
      ViewBag.Treat = _db.Treats.FirstOrDefault(treat => treat.TreatId == joinEntry.TreatId);
      return View(joinEntry);
    }

    [HttpPost, ActionName("DeleteTreat")]
    public ActionResult DeleteTreatConfirmed(int id)
    {
      var joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == id);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TreatId });
    }
  }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(PierresTreatsContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.Flavors)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      IQueryable<TreatFlavor> treatFlavors = _db.TreatFlavors.Where(entry => entry.TreatId == treat.TreatId);
      foreach (TreatFlavor entry in treatFlavors)
      {
        if (entry.FlavorId == FlavorId)
        {
          return RedirectToAction("Details", new { id = treat.TreatId });
        }
      }
      if (FlavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }
      

    [Authorize]
    public ActionResult DeleteFlavor(int id)
    {
      var joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == id);
      ViewBag.Flavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == joinEntry.FlavorId);
      ViewBag.Treat = _db.Treats.FirstOrDefault(treat => treat.TreatId == joinEntry.TreatId);
      return View(joinEntry);
    }

    [HttpPost, ActionName("DeleteFlavor")]
    public ActionResult DeleteFlavorConfirmed(int id)
    {
      var joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == id);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TreatId });
    }
  }
}

PierresTreats/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h4>@Html.Label($"{Model.FlavorName}")</h4>
<h4>Add Treat</h4>

@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  <div class="form-group">
    @Html.Label("Flavor")
    @Html.DropDownList("TreatId", null, new { @class="form-control" })
  </div>
  <input type="submit" value="Add Treat" class="btn btn-outline-dark" />
}

PierresTreats/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h4 class="view-title">Add Flavor</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <div class="form-group">
      @Html.Label("Flavor Name")
      @Html.TextBoxFor(model => model.FlavorName, new {@class="form-control"})
    </div>
    <input type="submit" value="Add Flavor" class="btn btn-outline-dark" />
  }
</div>

PierresTreats/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h4>@Html.Label($"{Model.FlavorName}")</h4>
<h4>Remove Flavor</h4>

@using (@Html.BeginForm())
{
  <h5>Confirm Flavor Removal</h5>
  <input type="submit" value="Confirm" class="btn btn-outline-dark" />
}

PierresTreats/Views/Flavors/DeleteFlavor.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.TreatFlavor
@using PierresTreats.Models;

<h4>Remove Treat</h4>
<h4>@Html.Label($"{ViewBag.Flavor.FlavorName} - {ViewBag.Treat.TreatName}")</h4>

@using (@Html.BeginForm())
{
  <h5>Confirm Treat Removal</h5>
  <input type="submit" value="Confirm" class="btn btn-outline-dark" />
}

PierresTreats/Views/Flavors/DeleteTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.TreatFlavor
@using PierresTreats.Models;

<h4>Remove Treat</h4>
<h4>@Html.Label($"{ViewBag.Flavor.FlavorName} - {ViewBag.Treat.TreatName}")</h4>

@using (@Html.BeginForm())
{
  <h5>Confirm Treat Removal</h5>
  <input type="submit" value="Confirm" class="btn btn-outline-dark" />
}

PierresTreats/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h3 id="header">@Html.Label($"{Model.FlavorName}")</h3>

@Html.ActionLink("Add Treat", "AddTreat", new { id = Model.FlavorId }, new { @id="btn-link" })
@Html.ActionLink("Edit Flavor Details", "Edit", new { id = Model.FlavorId }, new { @id="btn-link" })
@Html.ActionLink("Remove Flavor", "Delete", new { id = Model.FlavorId }, new { @id="btn-link" })

<h5>Treats</h5>
<hr />
@if (@Model.Treats.Count == 0)
{
  <h5>No Treats</h5>
} 
else
{
  @foreach(var join in Model.Treats)
  {
    <h5>@Html.ActionLink($"{join.Treat.TreatName}", "Details", "Treats", new { id = join.Treat.TreatId })</h5>
    @if (User.Identity.IsAuthenticated)
    {
      @Html.ActionLink("Remove Treat", "DeleteTreat", new { id = join.TreatFlavorId }, new { @id="btn-link" })
    }
  }
}

PierresTreats/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h4 class="view-title">@Html.Label($"{Model.FlavorName}")</h4>
<h4 class="view-title">Edit Flavor</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)
    <div class="form-group">
      @Html.Label("Flavor Name")
      @Html.TextBoxFor(model => model.FlavorName, new {@class="form-control"})
    </div>
    <input type="submit" value="Apply Changes" class="btn btn-outline-dark" />
  }
</div>

PierresTreats/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;
@model List<PierresTreats.Models.Flavor>;


<h3>Flavors</h3>
<hr />
<div class="flex container">
  @if (Model.Count == 0)
  {
    <h5>None.</h5>
  }
  @foreach (Flavor flavor in Model)
  {
    <h5>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</h5>
  }
</div>
<hr />

@Html.ActionLink("Add new Flavor", "Create", null, new { @id="btn-link" })